/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.sistemas.ed.vistas;

import pe.edu.unmsm.sistemas.ed.estructuras.ListaTermino;
import pe.edu.unmsm.sistemas.ed.estructuras.Termino;
import javax.swing.JOptionPane;
/**
 *
 * @author desandlope0
 */
public class PolinomioView extends javax.swing.JFrame {

    private ListaTermino polinomio = new ListaTermino();
     private ListaTermino polinomio2 = new ListaTermino();
    private ListaTermino polinomioDerivado= new ListaTermino();
    private ListaTermino polinomioIntegrado= new ListaTermino();

    /**
     * Creates new form PolinomioView
     */
    public PolinomioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpOpciones = new javax.swing.JTabbedPane();
        pnlPolinomio = new javax.swing.JPanel();
        pnlIntegracion = new javax.swing.JPanel();
        lblIntegracionAnalitica = new javax.swing.JLabel();
        txtLimiteInferiorIntAna = new javax.swing.JTextField();
        lblLimiteSuperiorIntAna = new javax.swing.JLabel();
        txtLimiteSuperiorIntAna = new javax.swing.JTextField();
        lblLimiteInferiorIntAna = new javax.swing.JLabel();
        btnObtenerIntegralAnalitica = new javax.swing.JButton();
        btnEvaluarIntegralAnalitica = new javax.swing.JButton();
        lblNumeroIntegraciones = new javax.swing.JLabel();
        txtNumeroIntegraciones = new javax.swing.JTextField();
        pnlDerivacion = new javax.swing.JPanel();
        lblDerivadaPunto = new javax.swing.JLabel();
        txtValorEvalDerivada = new javax.swing.JTextField();
        btnObtenerDerivada = new javax.swing.JButton();
        btnEvaluarDerivada = new javax.swing.JButton();
        lblNumeroDerivaciones = new javax.swing.JLabel();
        txtNumeroDerivaciones = new javax.swing.JTextField();
        pnlTerminos = new javax.swing.JPanel();
        btnAgregarTermino = new javax.swing.JButton();
        lblExponente = new javax.swing.JLabel();
        lblCoeficiente = new javax.swing.JLabel();
        txtExponente = new javax.swing.JTextField();
        txtCoeficiente = new javax.swing.JTextField();
        btnVerPolinomio = new javax.swing.JButton();
        pnlEvaluacionPolinomio = new javax.swing.JPanel();
        btnEvaluarPolinomio = new javax.swing.JButton();
        lblNumeroEvaluar = new javax.swing.JLabel();
        txtNumeroEvaluar = new javax.swing.JTextField();
        pnlMasOperaciones = new javax.swing.JPanel();
        multiplicarNumero = new javax.swing.JPanel();
        btnMultiplicarNumero = new javax.swing.JButton();
        lblPotenciaBinomioNewton = new javax.swing.JLabel();
        txtMultiplicarNumero = new javax.swing.JTextField();
        pnlIntegracionNumerica = new javax.swing.JPanel();
        lblLimitesIntegracionNumerica = new javax.swing.JLabel();
        txtLimiteInferiorIntNum = new javax.swing.JTextField();
        lblLimiteSuperiorIntNum = new javax.swing.JLabel();
        txtLimiteSuperiorIntNum = new javax.swing.JTextField();
        lblLimiteInferior = new javax.swing.JLabel();
        btnCalcularIntegralNumerica = new javax.swing.JButton();
        pnlTerminos1 = new javax.swing.JPanel();
        btnAgregarTermino1 = new javax.swing.JButton();
        lblExponente1 = new javax.swing.JLabel();
        lblCoeficiente1 = new javax.swing.JLabel();
        txtExponente1 = new javax.swing.JTextField();
        txtCoeficiente1 = new javax.swing.JTextField();
        btnVerPolinomio1 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        scrResultados = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        lblTituloResultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpOpciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pnlIntegracion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Integración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlIntegracion.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        lblIntegracionAnalitica.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblIntegracionAnalitica.setText("Límites");

        txtLimiteInferiorIntAna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblLimiteSuperiorIntAna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLimiteSuperiorIntAna.setText(" b");

        txtLimiteSuperiorIntAna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblLimiteInferiorIntAna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLimiteInferiorIntAna.setText("a");

        btnObtenerIntegralAnalitica.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnObtenerIntegralAnalitica.setText("Integrar");
        btnObtenerIntegralAnalitica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerIntegralAnaliticaActionPerformed(evt);
            }
        });

        btnEvaluarIntegralAnalitica.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEvaluarIntegralAnalitica.setText("Calcular");
        btnEvaluarIntegralAnalitica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarIntegralAnaliticaActionPerformed(evt);
            }
        });

        lblNumeroIntegraciones.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroIntegraciones.setText("Número de Integraciones");

        txtNumeroIntegraciones.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlIntegracionLayout = new javax.swing.GroupLayout(pnlIntegracion);
        pnlIntegracion.setLayout(pnlIntegracionLayout);
        pnlIntegracionLayout.setHorizontalGroup(
            pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntegracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlIntegracionLayout.createSequentialGroup()
                        .addComponent(lblIntegracionAnalitica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLimiteInferiorIntAna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLimiteInferiorIntAna, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblLimiteSuperiorIntAna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLimiteSuperiorIntAna, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIntegracionLayout.createSequentialGroup()
                        .addComponent(lblNumeroIntegraciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroIntegraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObtenerIntegralAnalitica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluarIntegralAnalitica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlIntegracionLayout.setVerticalGroup(
            pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntegracionLayout.createSequentialGroup()
                .addGroup(pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObtenerIntegralAnalitica)
                    .addComponent(txtNumeroIntegraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroIntegraciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIntegracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegracionAnalitica)
                    .addComponent(txtLimiteInferiorIntAna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimiteSuperiorIntAna)
                    .addComponent(txtLimiteSuperiorIntAna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimiteInferiorIntAna)
                    .addComponent(btnEvaluarIntegralAnalitica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDerivacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Derivación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlDerivacion.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        lblDerivadaPunto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblDerivadaPunto.setText("Derivada en un punto");

        txtValorEvalDerivada.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtValorEvalDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorEvalDerivadaActionPerformed(evt);
            }
        });

        btnObtenerDerivada.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnObtenerDerivada.setText("Derivar");
        btnObtenerDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerDerivadaActionPerformed(evt);
            }
        });

        btnEvaluarDerivada.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEvaluarDerivada.setText("Calcular");
        btnEvaluarDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarDerivadaActionPerformed(evt);
            }
        });

        lblNumeroDerivaciones.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroDerivaciones.setText("Número de Derivaciones");

        txtNumeroDerivaciones.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlDerivacionLayout = new javax.swing.GroupLayout(pnlDerivacion);
        pnlDerivacion.setLayout(pnlDerivacionLayout);
        pnlDerivacionLayout.setHorizontalGroup(
            pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDerivacionLayout.createSequentialGroup()
                .addGroup(pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDerivacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDerivadaPunto)
                        .addGap(36, 36, 36)
                        .addComponent(txtValorEvalDerivada))
                    .addGroup(pnlDerivacionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblNumeroDerivaciones)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroDerivaciones)))
                .addGap(18, 18, 18)
                .addGroup(pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEvaluarDerivada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtenerDerivada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlDerivacionLayout.setVerticalGroup(
            pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDerivacionLayout.createSequentialGroup()
                .addGroup(pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObtenerDerivada)
                    .addComponent(txtNumeroDerivaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroDerivaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDerivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDerivadaPunto)
                    .addComponent(txtValorEvalDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluarDerivada))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnlTerminos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Termino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnAgregarTermino.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarTermino.setText("Agregar");
        btnAgregarTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTerminoActionPerformed(evt);
            }
        });

        lblExponente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblExponente.setText("Exponente");

        lblCoeficiente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCoeficiente.setText("Coeficiente");

        txtExponente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtExponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExponenteActionPerformed(evt);
            }
        });

        txtCoeficiente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCoeficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoeficienteActionPerformed(evt);
            }
        });

        btnVerPolinomio.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnVerPolinomio.setText("Ver Polinomio");
        btnVerPolinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPolinomioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTerminosLayout = new javax.swing.GroupLayout(pnlTerminos);
        pnlTerminos.setLayout(pnlTerminosLayout);
        pnlTerminosLayout.setHorizontalGroup(
            pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTerminosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTerminosLayout.createSequentialGroup()
                        .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExponente)
                            .addComponent(lblCoeficiente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExponente)
                            .addComponent(txtCoeficiente)))
                    .addGroup(pnlTerminosLayout.createSequentialGroup()
                        .addComponent(btnVerPolinomio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarTermino)))
                .addContainerGap())
        );
        pnlTerminosLayout.setVerticalGroup(
            pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExponente)
                    .addComponent(txtExponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoeficiente)
                    .addComponent(txtCoeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlTerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTermino)
                    .addComponent(btnVerPolinomio))
                .addContainerGap())
        );

        pnlEvaluacionPolinomio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnEvaluarPolinomio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEvaluarPolinomio.setText("Evaluar");
        btnEvaluarPolinomio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarPolinomioActionPerformed(evt);
            }
        });

        lblNumeroEvaluar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroEvaluar.setText("Número");

        txtNumeroEvaluar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlEvaluacionPolinomioLayout = new javax.swing.GroupLayout(pnlEvaluacionPolinomio);
        pnlEvaluacionPolinomio.setLayout(pnlEvaluacionPolinomioLayout);
        pnlEvaluacionPolinomioLayout.setHorizontalGroup(
            pnlEvaluacionPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvaluacionPolinomioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEvaluacionPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEvaluacionPolinomioLayout.createSequentialGroup()
                        .addComponent(lblNumeroEvaluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroEvaluar))
                    .addGroup(pnlEvaluacionPolinomioLayout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(btnEvaluarPolinomio)))
                .addContainerGap())
        );
        pnlEvaluacionPolinomioLayout.setVerticalGroup(
            pnlEvaluacionPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvaluacionPolinomioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEvaluacionPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroEvaluar)
                    .addComponent(txtNumeroEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEvaluarPolinomio)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout pnlPolinomioLayout = new javax.swing.GroupLayout(pnlPolinomio);
        pnlPolinomio.setLayout(pnlPolinomioLayout);
        pnlPolinomioLayout.setHorizontalGroup(
            pnlPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolinomioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEvaluacionPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlIntegracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDerivacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPolinomioLayout.setVerticalGroup(
            pnlPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolinomioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPolinomioLayout.createSequentialGroup()
                        .addGroup(pnlPolinomioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDerivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlEvaluacionPolinomio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlIntegracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpOpciones.addTab("Operaciones básicas", pnlPolinomio);

        multiplicarNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Multiplicar por un numero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnMultiplicarNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnMultiplicarNumero.setText("Multiplicar");
        btnMultiplicarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarNumeroActionPerformed(evt);
            }
        });

        lblPotenciaBinomioNewton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPotenciaBinomioNewton.setText("numero");

        txtMultiplicarNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtMultiplicarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultiplicarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout multiplicarNumeroLayout = new javax.swing.GroupLayout(multiplicarNumero);
        multiplicarNumero.setLayout(multiplicarNumeroLayout);
        multiplicarNumeroLayout.setHorizontalGroup(
            multiplicarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiplicarNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(multiplicarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMultiplicarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(multiplicarNumeroLayout.createSequentialGroup()
                        .addComponent(lblPotenciaBinomioNewton)
                        .addGap(26, 26, 26)
                        .addComponent(txtMultiplicarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        multiplicarNumeroLayout.setVerticalGroup(
            multiplicarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplicarNumeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(multiplicarNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPotenciaBinomioNewton)
                    .addComponent(txtMultiplicarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiplicarNumero)
                .addGap(40, 40, 40))
        );

        pnlIntegracionNumerica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Integración Numérica de 1/(1+e^-x)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlIntegracionNumerica.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N

        lblLimitesIntegracionNumerica.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLimitesIntegracionNumerica.setText("Límites");

        txtLimiteInferiorIntNum.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblLimiteSuperiorIntNum.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLimiteSuperiorIntNum.setText(" b");

        txtLimiteSuperiorIntNum.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblLimiteInferior.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLimiteInferior.setText("a");

        btnCalcularIntegralNumerica.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnCalcularIntegralNumerica.setText("Calcular");
        btnCalcularIntegralNumerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIntegralNumericaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIntegracionNumericaLayout = new javax.swing.GroupLayout(pnlIntegracionNumerica);
        pnlIntegracionNumerica.setLayout(pnlIntegracionNumericaLayout);
        pnlIntegracionNumericaLayout.setHorizontalGroup(
            pnlIntegracionNumericaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntegracionNumericaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLimitesIntegracionNumerica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLimiteInferior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLimiteInferiorIntNum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLimiteSuperiorIntNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLimiteSuperiorIntNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularIntegralNumerica, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIntegracionNumericaLayout.setVerticalGroup(
            pnlIntegracionNumericaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIntegracionNumericaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlIntegracionNumericaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimitesIntegracionNumerica)
                    .addComponent(txtLimiteInferiorIntNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimiteSuperiorIntNum)
                    .addComponent(txtLimiteSuperiorIntNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimiteInferior)
                    .addComponent(btnCalcularIntegralNumerica))
                .addContainerGap())
        );

        pnlTerminos1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Multiplicar por un monomio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnAgregarTermino1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAgregarTermino1.setText("Agregar");
        btnAgregarTermino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTermino1ActionPerformed(evt);
            }
        });

        lblExponente1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblExponente1.setText("Exponente");

        lblCoeficiente1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblCoeficiente1.setText("Coeficiente");

        txtExponente1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtExponente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExponente1ActionPerformed(evt);
            }
        });

        txtCoeficiente1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCoeficiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoeficiente1ActionPerformed(evt);
            }
        });

        btnVerPolinomio1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnVerPolinomio1.setText("Ver Polinomio");
        btnVerPolinomio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPolinomio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTerminos1Layout = new javax.swing.GroupLayout(pnlTerminos1);
        pnlTerminos1.setLayout(pnlTerminos1Layout);
        pnlTerminos1Layout.setHorizontalGroup(
            pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTerminos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTerminos1Layout.createSequentialGroup()
                        .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExponente1)
                            .addComponent(lblCoeficiente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExponente1)
                            .addComponent(txtCoeficiente1)))
                    .addGroup(pnlTerminos1Layout.createSequentialGroup()
                        .addComponent(btnVerPolinomio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarTermino1)))
                .addContainerGap())
        );
        pnlTerminos1Layout.setVerticalGroup(
            pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTerminos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExponente1)
                    .addComponent(txtExponente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoeficiente1)
                    .addComponent(txtCoeficiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlTerminos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTermino1)
                    .addComponent(btnVerPolinomio1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMasOperacionesLayout = new javax.swing.GroupLayout(pnlMasOperaciones);
        pnlMasOperaciones.setLayout(pnlMasOperacionesLayout);
        pnlMasOperacionesLayout.setHorizontalGroup(
            pnlMasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasOperacionesLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(pnlMasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMasOperacionesLayout.createSequentialGroup()
                        .addComponent(multiplicarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTerminos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMasOperacionesLayout.createSequentialGroup()
                        .addComponent(pnlIntegracionNumerica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
        pnlMasOperacionesLayout.setVerticalGroup(
            pnlMasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMasOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMasOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTerminos1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(pnlIntegracionNumerica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        multiplicarNumero.getAccessibleContext().setAccessibleName("Multiplicar por un Número");

        tpOpciones.addTab("Más operaciones", pnlMasOperaciones);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("ET02 - Representación de polinomios");

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        scrResultados.setViewportView(txtResultados);

        lblTituloResultados.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTituloResultados.setText("Visualización de resultados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(257, 257, 257))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrResultados)
                    .addComponent(tpOpciones, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloResultados)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTerminoActionPerformed
        // Leer los datos de entrada
        int exponente = Integer.parseInt(txtExponente.getText());
        double coeficiente = Double.parseDouble(txtCoeficiente.getText());
        
        //Instanciar el elemento a guardar en el nodo
        Termino nuevoTermino = new Termino(exponente, coeficiente);
        //Agregar el elemento a la lista
        polinomio.agregarTermino(nuevoTermino);
        //Visualizar el polinomio actual
        txtResultados.setText(polinomio.toString());
        //visualizarPolinomio(polinomio, "actual");
        limpiarCampos();
    }//GEN-LAST:event_btnAgregarTerminoActionPerformed

    private void btnEvaluarPolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarPolinomioActionPerformed
        //Leer los datos de entrada
        double numero = Double.parseDouble(txtNumeroEvaluar.getText());
        //Procesar 
        double resultado = polinomio.evaluar(numero);
        //Mostrar el resultado:
        txtResultados.setText("El resultado de evaluar el polinomio en " + numero + " es " + resultado);
        limpiarCampos();
    }//GEN-LAST:event_btnEvaluarPolinomioActionPerformed

    private void btnVerPolinomioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPolinomioActionPerformed
        visualizarPolinomio(polinomio, "actual");
        limpiarCampos();
    }//GEN-LAST:event_btnVerPolinomioActionPerformed

    private void btnObtenerDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerDerivadaActionPerformed
        //Leer los datos de entrada
        int numeroDerivaciones = Integer.parseInt(txtNumeroDerivaciones.getText());
        //Obtener la derivada n-ésima.
        //ListaTermino polinomioDerivado= new ListaTermino();
        polinomioDerivado = polinomio.derivar(polinomio, numeroDerivaciones);
        //Mostrar resultados
        visualizarPolinomio(polinomioDerivado, "derivado");
        limpiarCampos();
    }//GEN-LAST:event_btnObtenerDerivadaActionPerformed

    private void btnEvaluarDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarDerivadaActionPerformed
        //Leer los datos de entrada
        double valorEvaluado = Double.parseDouble(txtValorEvalDerivada.getText());
        double resultado = polinomioDerivado.evaluar(valorEvaluado);
        //Mostrar el resultado:
        txtResultados.setText("El resultado de evaluar el polinomio derivado en " + valorEvaluado + " es " + resultado);
 
        //double numeroDerivaciones = Double.parseDouble(txtNumeroDerivaciones.getText());
        //Obtener el valor en la derivada n-ésima.
//        double valorPolinomioDerivado = polinomio.derivar(numeroDerivaciones, valorEvaluado);
        //Mostrar resultados
   //     txtResultados.setText("El resultado de evaluar la " + numeroDerivaciones
   //             + "º derivada del polinomio en " + valorEvaluado + " es " + valorPolinomioDerivado);
        limpiarCampos();
    }//GEN-LAST:event_btnEvaluarDerivadaActionPerformed

    private void btnObtenerIntegralAnaliticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerIntegralAnaliticaActionPerformed
        //Leer los datos de entrada
        int numeroIntegraciones = Integer.parseInt(txtNumeroIntegraciones.getText());
        //Obtener la integral n-ésima.
        polinomioIntegrado = polinomio.integrar(numeroIntegraciones);
        //Mostrar resultados
        String polRepCadena = "El polinomio integrado es \n" + polinomioIntegrado.toStringIntegrado();
        txtResultados.setText(polRepCadena);
        //limpiarCampos();
    }//GEN-LAST:event_btnObtenerIntegralAnaliticaActionPerformed

    private void btnEvaluarIntegralAnaliticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarIntegralAnaliticaActionPerformed
        //Leer los datos de entrada
        double limiteInferior = Double.parseDouble(txtLimiteInferiorIntAna.getText());
        double limiteSuperior = Double.parseDouble(txtLimiteSuperiorIntAna.getText());
        int numeroIntegraciones = Integer.parseInt(txtNumeroIntegraciones.getText());
        //Obtener el valor en la integral n-ésima.
        double valorPolinomioIntegrado = polinomioIntegrado.evaluar(limiteSuperior) - polinomioIntegrado.evaluar(limiteInferior);
        //Mostrar resultados
        txtResultados.setText("El resultado de evaluar la " + numeroIntegraciones
                + "º integral del polinomio en " + "[" + limiteInferior + "," + limiteSuperior + "]"
                + " es " + valorPolinomioIntegrado);
        limpiarCampos();
    }//GEN-LAST:event_btnEvaluarIntegralAnaliticaActionPerformed

    private void btnMultiplicarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarNumeroActionPerformed
        //Leer los datos de entrada
        int numero = Integer.parseInt(txtMultiplicarNumero.getText());
        //Multiplicar un numero por un polinomio
        ListaTermino polinomioMultiplicado = new ListaTermino();
        polinomioMultiplicado = polinomioMultiplicado.multiplicarNumero(numero);
        //Mostrar resultados
        txtResultados.setText("El resultado de multiplicar la expresion por " + numero 
                + " es " + polinomioMultiplicado.toString() );
        limpiarCampos();
    }//GEN-LAST:event_btnMultiplicarNumeroActionPerformed

    private void btnCalcularIntegralNumericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIntegralNumericaActionPerformed
        //Leer los datos de entrada
        int limiteInferior = Integer.parseInt(txtLimiteInferiorIntNum.getText());
        int limiteSuperior = Integer.parseInt(txtLimiteSuperiorIntNum.getText());
        //Obtener el valor en la integral n-ésima.
        //double valorIntegralSigmoidal = ListaTermino.integrarSigmoidalNumericamente(limiteInferior, limiteSuperior);
        //Mostrar resultados
      //  txtResultados.setText("El resultado de evaluar la integral de 1/(1+e^-x)) en " + "[" + limiteInferior + "," + limiteSuperior + "]"
      //          + " es " + valorIntegralSigmoidal);
        limpiarCampos();
    }//GEN-LAST:event_btnCalcularIntegralNumericaActionPerformed

    private void txtExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExponenteActionPerformed
        // TODO add your handling code here:
        int exponente = leerNumero(txtExponente);
    
    }//GEN-LAST:event_txtExponenteActionPerformed

    private void txtCoeficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoeficienteActionPerformed
        // TODO add your handling code here:
        double coeficiente = leerNumero(txtCoeficiente);
        
    }//GEN-LAST:event_txtCoeficienteActionPerformed

    private void txtValorEvalDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorEvalDerivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorEvalDerivadaActionPerformed

    private void btnAgregarTermino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTermino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarTermino1ActionPerformed

    private void txtExponente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExponente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExponente1ActionPerformed

    private void txtCoeficiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoeficiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoeficiente1ActionPerformed

    private void btnVerPolinomio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPolinomio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerPolinomio1ActionPerformed

    private void txtMultiplicarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultiplicarNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultiplicarNumeroActionPerformed

    private void visualizarPolinomio(ListaTermino polinomio, String caracteristica) {
            
        String polRepCadena = "El polinomio " + caracteristica + " es \n" + polinomio;
        txtResultados.setText(polRepCadena);
    }
    private int leerNumero(javax.swing.JTextField txt) {
        int numero = -1;
        try {
            numero = Integer.parseInt(txt.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "No es un número");
            limpiarEntrada(txt);
        }
        return numero;
    }
    private void limpiarEntrada(javax.swing.JTextField txt) {
        txt.setText("");
        txt.requestFocus();
    }
    private void limpiarCampos() {
        txtCoeficiente.setText("");
        txtExponente.setText("");
        //txtGradoPolinomioLegendre.setText("");
        txtLimiteInferiorIntAna.setText("");
        txtLimiteSuperiorIntAna.setText("");
        txtLimiteInferiorIntNum.setText("");
        txtLimiteSuperiorIntNum.setText("");
        txtNumeroDerivaciones.setText("");
        txtNumeroEvaluar.setText("");
        txtNumeroIntegraciones.setText("");
        txtMultiplicarNumero.setText("");
        txtValorEvalDerivada.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolinomioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolinomioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTermino;
    private javax.swing.JButton btnAgregarTermino1;
    private javax.swing.JButton btnCalcularIntegralNumerica;
    private javax.swing.JButton btnEvaluarDerivada;
    private javax.swing.JButton btnEvaluarIntegralAnalitica;
    private javax.swing.JButton btnEvaluarPolinomio;
    private javax.swing.JButton btnMultiplicarNumero;
    private javax.swing.JButton btnObtenerDerivada;
    private javax.swing.JButton btnObtenerIntegralAnalitica;
    private javax.swing.JButton btnVerPolinomio;
    private javax.swing.JButton btnVerPolinomio1;
    private javax.swing.JLabel lblCoeficiente;
    private javax.swing.JLabel lblCoeficiente1;
    private javax.swing.JLabel lblDerivadaPunto;
    private javax.swing.JLabel lblExponente;
    private javax.swing.JLabel lblExponente1;
    private javax.swing.JLabel lblIntegracionAnalitica;
    private javax.swing.JLabel lblLimiteInferior;
    private javax.swing.JLabel lblLimiteInferiorIntAna;
    private javax.swing.JLabel lblLimiteSuperiorIntAna;
    private javax.swing.JLabel lblLimiteSuperiorIntNum;
    private javax.swing.JLabel lblLimitesIntegracionNumerica;
    private javax.swing.JLabel lblNumeroDerivaciones;
    private javax.swing.JLabel lblNumeroEvaluar;
    private javax.swing.JLabel lblNumeroIntegraciones;
    private javax.swing.JLabel lblPotenciaBinomioNewton;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloResultados;
    private javax.swing.JPanel multiplicarNumero;
    private javax.swing.JPanel pnlDerivacion;
    private javax.swing.JPanel pnlEvaluacionPolinomio;
    private javax.swing.JPanel pnlIntegracion;
    private javax.swing.JPanel pnlIntegracionNumerica;
    private javax.swing.JPanel pnlMasOperaciones;
    private javax.swing.JPanel pnlPolinomio;
    private javax.swing.JPanel pnlTerminos;
    private javax.swing.JPanel pnlTerminos1;
    private javax.swing.JScrollPane scrResultados;
    private javax.swing.JTabbedPane tpOpciones;
    private javax.swing.JTextField txtCoeficiente;
    private javax.swing.JTextField txtCoeficiente1;
    private javax.swing.JTextField txtExponente;
    private javax.swing.JTextField txtExponente1;
    private javax.swing.JTextField txtLimiteInferiorIntAna;
    private javax.swing.JTextField txtLimiteInferiorIntNum;
    private javax.swing.JTextField txtLimiteSuperiorIntAna;
    private javax.swing.JTextField txtLimiteSuperiorIntNum;
    private javax.swing.JTextField txtMultiplicarNumero;
    private javax.swing.JTextField txtNumeroDerivaciones;
    private javax.swing.JTextField txtNumeroEvaluar;
    private javax.swing.JTextField txtNumeroIntegraciones;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtValorEvalDerivada;
    // End of variables declaration//GEN-END:variables
}
